name: Build and Publish Docker Image

on:
  push:
    branches: [main, master]
    tags: ["v*"]
  pull_request:
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Log in to Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Taskfile
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push multi-platform Docker image
        if: github.event_name != 'pull_request'
        env:
          RUN_NUMBER: ${{ github.run_number }}
          CI: true
          OWNER: ${{ github.repository_owner }}
        run: task build-ci

      - name: Build single-platform Docker image (PR only)
        if: github.event_name == 'pull_request'
        env:
          RUN_NUMBER: ${{ github.run_number }}
          CI: false
          OWNER: ${{ github.repository_owner }}
        run: task build-ci
